import {Project, About, Contact} from './Classes'
import LinkedInLogo from '../images/linkedin-logo.png'
import MailLogo from '../images/mail-logo.png'
import GithubLogo from '../images/github-logo.png'
import pubGolfBanner from '../images/pub-golf-banner.png'
import fantasyBanner from '../images/fantasy-banner.jpg'
import portfolioBanner from '../images/portfolio-banner.png'
import tacticoBanner from '../images/tactico-banner.png'

const tactico = new Project(1, "Tactico", "A full-stack web app built to help small-sided sports teams manage their season and engage their players. Designed and developed solo from scratch using React, Node.js, and MongoDB, Tactico is a monthly subscription service that lets teams create custom hubs- tracking fixtures, results, goals, assists, and more. " +
    "Tactico uses Snapchat authentication, enabling users to log in seamlessly and integrate their Bitmoji avatars for a fun, personalized experience. It also features a fantasy-style prediction game, where players earn points for accurately predicting match outcomes. " +
    "This project was an opportunity to explore third-party authentication flows, including handling OAuth tokens, securely managing sessions, and ensuring proper access control. Because Tactico is a live project, I implemented database-level restrictions to prevent unauthorized reads/writes, along with validation and sanitization at both the client and server levels.\n" +
    "It also marked my first time deploying a live backend, using Railway for hosting and continuous deployment. This experience helped me understand backend infrastructure, environment management, and the importance of secure API design in a production environment.", "Personal project", "2025", "React, Node.js, MongoDB, OAuth, CI/CD", tacticoBanner, "https://jackmarchant1.github.io/Tactico-Landing/");
const pubGolf = new Project(2, "Pub Golf", "A full-stack social web app built with .NET, Azure, and SQL Server, created in collaboration with a coursemate during university. Pub Golf lets users design and share themed pub crawl courses, turning a night out into a competitive, gamified experience.\n" +
    "Users can sign up, create custom \"courses\" by selecting pubs and assigning drinks to each \"hole\", and then publish the course for others to join using a unique code. Once joined, players follow along live, submitting scores for each hole directly from their own devices. The app also features a community-driven course marketplace, where users can browse, rate, and clone previously created courses- bringing a social layer to the game. " +
    "This project was a deep dive into Azure-based deployment and services, including setting up cloud-hosted APIs, managing relational data with SQL Server, and implementing secure user authentication with ASP.NET Identity. I also gained valuable experience with live data syncing, session management for multi-user participation, and optimizing SQL queries for performance across dynamic course data. Because the app is built to handle live user interactions during events, we focused heavily on real-time reliability, database integrity, and clean UX across devices- ","Pair project","2024","ASP.NET, C#, Azure, SQL", pubGolfBanner, "https://pub-golf-dev.azurewebsites.net/");
const fantasyGaff = new Project(3, "Fantasy Gaffer", "Fantasy72 was the first full software project I built-an iOS fantasy football app focused on the three professional English leagues below the Premier League.\n" +
    "Developed solo during my final year of high school using Swiftul, it aimed to bring the full fantasy sports experience to a niche audience underserved by major platforms.\n" +
    "The app featured full user account creation, league management with friend invites, live point updates based on real match performance, and core team management features like transfers and substitutions. It was built using Apple's SwiftUl framework\n" +
    "—my first time working with it-which allowed me to design and build a clean, modern mobile interface that matched the aesthetic of native iOS apps.\n" +
    "Fantasy72 organically grew to over 1,000 users purely through word of mouth.\n" +
    "Building and managing a real-time scoring system, integrating match data, and handling user state across the app gave me my first exposure to building production-grade features like data syncing, session persistence, and UI responsiveness at scale. While I eventually had to sunset the app due to server costs and legal limitations on monetization, Fantasy72 was a formative project that taught me how to take an idea from concept to a polished, real-world product.","Personal project","2020","Swift (SwiftUI), Node.js, Firebase", fantasyBanner);
const engimaMachine = new Project(4, "Enigma Machine","As the final project of a functional programming module at university, I recreated a fully functioning wartime Enigma Machine. The final product would take a String and any enigma configuration (3 rotors, initial offsets, and a steckerboard), and encode the given string through the given enigma machine. As the machine was designed to be symmetric and reversible, decoding a message is as simple as passing the encoded message through the same function, given the machine was in the same configuration as it was when the message was first encoded. This project was different to anything that I had done before, and as my first experience with a functional programming language, I definitely had to change the way I thought about solving the problem. Although I doubt I will use funtional languages on a day-to-day basis in the future, the project gave me the ability to think about projects in different ways, and since completing this module I have definitely seen that functional mindset coming into it when I have been struggling to solve problems in the more conventinoal ways that I would before. I wrote a 9 page accompanying LaTex report for the project documenting my design and testing for each section which received a final grade of 92%. Per university guidelines, I cannot make the source code of the project public, however I would be happy to share upon request.","University project","2023","Haskell", undefined, "https://github.com/jackmarchant1/EnigmaMachine");
const placementAdvisor = new Project(5, "Placement Advisor","As a second year project, I was a part of a team that was assigned a real-world client with a real-world need. A doctor from a local medical school had noticed that the best placements and internships would often be missed out on by Widening Participation (WP) students due to a lack of knowledge of the best placements and contacts to get involved with them. Our task was to create a 'trip advisor style' site, allowing a collation of available medical placements/internships to be put into one place, along with comments and information from previous students who had taken the elective, and contact details for relevant people at the elective. I took a leadership role in this project, and had a big input over the full stack of the ruby on rails project. The project presented many challenges and taught me a lot about working in an AGILE team as well as how to best communicate with a client, both with gathering requirements and presenting iterations of our system. The client was extremely happy with the final project, achieving a first class grade for the final iteration of the project, judging the system and communication.","University/Client project","2023","Ruby on Rails, HAML, SQL");
const portfolioReact = new Project(6, "Portfolio Site","This website! " +
    "This site was designed and built entirely from scratch. I wanted this site to not only be a useful way to compile projects and information about me, but to also be a spectacle in and of itself that showcased my creativity and ability to bring exciting ideas to life. " +
    "This project was my first ever experience with using React. It is a constant work in progress and I aim to use it as a way to continue to push myself into learning new technologies and programming practices and showcasing the results. ",
    "Personal project",
    "2023",
    "ReactJS, Github Pages",
    portfolioBanner);

export const projectArray = [tactico, pubGolf, fantasyGaff, engimaMachine, portfolioReact];

const aboutMe = new About(1, "Myself", "Hi👋. I’m a recent computer science graduate from the University of Sheffield in the United Kingdom. I now live in Connecticut, USA. Having graduated with a first-class honours degree, I've developed a strong foundation in software engineering, data structures, and algorithms. My journey into software development was sparked by an early interest in mobile app creation, and over the years, I've expanded my expertise to full-stack web development.\n" +
    "I have a deep passion for building products from the ground up, and I thrive on turning ideas into fully realised software solutions. During my time at university, I had the opportunity to lecture a cohort of first year students as a teaching assistant for a data structures and algorithms course, as well as serving as an undergraduate ambassador, visiting local secondary schools to inspire future engineers. In my spare time, I keep up with the latest developments in the tech world, particularly startups with exciting missions. I'm always eager to learn and collaborate on projects that challenge the status quo and push the boundaries of innovation.\n" +
    "Whether working independently or in a team, I bring a sense of ownership, creativity, and a strong desire to contribute to building software that makes an impact.", "");
const aboutCompany = new About(2, "My Company", "Mid 2023, I started a software engineering company with a university friend, Forge38. The company has worked on a number of small software projects for clients, and we look to continue building it. For more info, reach out with an email below.", "");
export const aboutArray = [aboutMe, aboutCompany]

const linkedIn = new Contact(1, "LinkedIn", LinkedInLogo, "https://www.linkedin.com/in/jack-marchant-98b122124/");
const mail = new Contact(2, "Mail", MailLogo, "mailto:me@jackmarchantt.dev");
const github = new Contact(3, "Github", GithubLogo, "https://github.com/jackmarchant1/");
export const contactArray = [linkedIn, mail, github]